version: '2'

services:

  ############################
  ##### Semantic Lookup Service #####
  ############################

  semantic-lookup-service:
    image: iassetplatform/semantic-lookup-service:staging
    ports:
      - "8084:8084"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - SOLR_HOST=http://solr:8983/solr/
    mem_limit: 1000m
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    networks:
      - infra
  
  ############################
  ##### Registry Service #####
  ############################

  registry-service:
    image: iassetplatform/asset-registry:staging
    ports:
      - "8085:8085"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
    mem_limit: 1000m
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    networks:
      - infra

  ############################
  ##### Identity Service #####
  ############################
 
  identity-service:
    image: iassetplatform/identity-service:staging
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms64m
    mem_limit: 1000m
    ports:
      - "9096:9096"
    networks:
      - infra

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: iassetplatform/business-process-service:staging
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
    mem_limit: 2000m
    ports:
      - "8086:8086"
    networks:
      - infra

  ##############################
  ####### Indexing Service #####
  ##############################

  asset-indexing-service:
    image: iassetplatform/indexing-service:staging
    ports:
      - "9101:8090"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - SOLR_HOST=http://solr:8983/solr/
    mem_limit: 1000m
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    networks:
      - infra

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalog-service-srdc:
    image: iassetplatform/catalogue-service-micro:staging
    ports:
      - "10095:8095"
    environment:
      - _JAVA_OPTIONS=-Xmx768m -Xms50m
    mem_limit: 2000m
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    networks:
      - infra

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: iassetplatform/frontend-service:staging
    ports:
      - "8081:8080"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms50m
    mem_limit: 1000m
    networks:
      - infra
    depends_on:
      - frontend-service-sidecar
  
  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 1000m
    networks:
      - infra
 
  ###############################
  #### Data Channel Service #####
  ###############################

  data-channel-service:
    image: iassetplatform/data-channel-service:staging
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    mem_limit: 1000m
    ports:
      - "9099:9099"
    networks:
      - infra

  ###############################
  #### Data Pipes #####
  ###############################

  data-pipes:
    image: nimbleplatform/data-pipes:staging
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    mem_limit: 500m
    ports:
      - "8082:8080"
    networks:
      - infra

  ###############################
  ## Tracking Analysis Service ##
  ###############################

  tracking-analysis-service:
    image: nimbleplatform/tracking-analysis-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    mem_limit: 400m
    ports:
      - "9100:9100"
    networks:
      - infra

  ###############################
  ## Data Aggregation Service ###
  ###############################

  data-aggregation-service:
    image: iassetplatform/data-aggregation-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    mem_limit: 700m
    networks:
      - infra

  ###############################
  ######## Trust Service ########
  ###############################

  trust-service:
    image: nimbleplatform/trust-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      PORT: 9098
      _JAVA_OPTIONS: -Xmx256m -Xms128m
    mem_limit: 800m
    ports:
      - "9098:9098"
    networks:
      - infra

  ###############################
  ######## Delegate Service ########
  ###############################
  delegate-service:
    image: nimbleplatform/delegate-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars_delegate
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms128m
    mem_limit: 1000m
    ports:
      - "9265:8080"
    networks:
      - infra

  ###############################
  ### Distribution Network  #####
  ###############################

  distribution-network:
    image: iassetplatform/distribution-network:staging
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka1
      - kafka2
      - kafka3
    # Staging deployment: (on Dockerhub and Jenkins), copy from iasset/distribution-network
    environment:
      IASSET_SERVER: https://iasset.salzburgresearch.at
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://${BINARY_CONTENT_DB_USERNAME}:${BINARY_CONTENT_DB_PASSWORD}@$staging-main-db:${BINARY_CONTENT_DB_PORT:-5432}/distributionnetworkdb
      KAFKA_BOOTSTRAP_SERVER: kafka1:19092,kafka2:19093,kafka3:19094
    ports:
      - "1908:1908"
#    network_mode: host
    networks:
      - infra
    restart: always

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - infra

  zoo2:
    image: zookeeper:3.4.9
    hostname: zoo2
    ports:
      - "2182:2182"
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2182
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - infra

  zoo3:
    image: zookeeper:3.4.9
    hostname: zoo3
    ports:
      - "2183:2183"
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2183
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - infra

  kafka1:
    image: confluentinc/cp-kafka:6.1.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - infra

  kafka2:
    image: confluentinc/cp-kafka:6.1.0
    hostname: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - infra

  kafka3:
    image: confluentinc/cp-kafka:6.1.0
    hostname: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - infra

networks:
  infra:
    external:
      name: iassetinfrastaging_default
